### ISSUE TITLE
Sitemap with no items

### ISSUE THREAD

**Issue by mkly** [evert/sitemap-php#2]
Hello,
Looks like I came across an issue you fixed in your fork earlier this year.

https://github.com/evert/sitemap-php/commit/56e8ed18ddf834ebd61afb90f714fba0a1273996

https://github.com/mkly/sitemap-php/commit/bae04562fe11bb2af14b1b3e5cead83e9aeacb35

The fix you have will not close the sitemap xml, whereas my patch closed the xml automatically. I imagine this was done to allow someone to handle the logic themselves outside the library to close the xml. Anyhow, just mentioning my change in case you might prefer it.

Thanks,
Mike

**Comment by evert** [comment]
This was fixed, a very long time after this issue was posted though. sorry -_-
