### ISSUE TITLE
Add gzip compression

### ISSUE THREAD

**Issue by tvb** [evert/sitemap-php#3]
Subject says it all.

**Comment by maxbanton** [comment]
+1

**Comment by rockymontana** [comment]
+1

**Comment by mablae** [comment]
Out of the scope of this library,
gzip compression should be done when delivering the file. 

It is activated by setting correct config values in .htaccess or nginx config.

**Comment by evert** [comment]
I tend to agree... "something else" should really do the compression. This is much more of a general concern than specific to sitemaps.
